### ISSUE TITLE
Fail gracefully

### ISSUE THREAD

**Issue by peddinti** [intercom/intercom-ruby#144]
For some of the actions like Find and others, when nothing matching is found, the gem throws and expection .. but as a general practice in ruby, i think it makes more sense to return a nil, so the failure can be graceful and developer can handle the special case when return object is nil.

**Comment by bobjflong** [comment]
Hi @peddinti , first off thanks for the report! We've chosen to use exceptions to signify failure here, because it forces the users of the API to handle those errors - instead of letting the failure propagate as a nil. If someone misses a nil, then it is likely to re-emerge as a `NoMethodError: undefined method for nil:NilClass` somewhere else in their code base. But if a `Intercom::ResourceNotFound` is thrown (and not handled) it is more obvious where the problem is.
