### ISSUE TITLE
Should this throw so many exceptions?

### ISSUE THREAD

**Issue by msfeldstein** [intercom/intercom-ruby#148]
Is there a reason the gem throws exceptions whenever it fails?  Given that the service is down today, all of our Intercom calls are throwing an Intercom::ServiceUnavailableError exception.  All of our analytics code is wrapped in an exception handler so that it can't hurt the user experience when it fails, but it did lose all the rest of our non-intercom analytics data points.

Given that intercom data is not product-critical it seems like the gem should just return an error code rather than throwing an exception.

**Comment by msfeldstein** [comment]
I guess this is more of a question than a bug, whats the reasoning for choosing exceptions over error codes?

**Comment by bobjflong** [comment]
hi @msfeldstein, thanks for raising this.

We've had to make some tough decisions with how we propagate errors. Some people prefer exceptions;
some prefer nils; and some prefer error objects/codes. Balancing these preferences alongside our
wish to provide an idiomatic gem has brought us to use the current mechanism of [very specific
exceptions](https://github.com/intercom/intercom-ruby#errors). I think that the most important thing for us is to signal our failure loudly - so that erroneous data does not get propagated through our customers' systems. In other words, if you see a `Intercom::ServiceUnavailableError` you know exactly what the problem is. We've taken your comments on board however - and please let us know if you have any other feedback.
