### ISSUE TITLE
Intercom event create with delayed job - undefined method `tr' for nil:NilClass

### ISSUE THREAD

**Issue by constantm** [intercom/intercom-ruby#165]
Not sure if this is directly related to creating an event using delayed_job, but it worked perfectly fine before the API changed from using `Intercom::Events.create` (which I didn't get any deprecation notices until it just stopped working today after a bundle update?)

```ruby
def log_intercom_event( event, meta_data={} )
  intercom = Intercom::Client.new(app_id: Rails.application.secrets.intercom_app_id, api_key: Rails.application.secrets.intercom_api_key)
  intercom.events.delay.create(last_request_at: Time.now.to_i, :event_name => event, :created_at => Time.now.to_i, user_id: current_user.id,:email => current_user.email, metadata: meta_data )
end
```

Calling `log_intercom_event('Client did something')` creates a delayed job, which fails with the following error:

```ruby
"undefined method `tr' for nil:NilClass
/home/user/.rbenv/versions/2.2.2/lib/ruby/2.2.0/cgi/util.rb:18:in `unescape'
/var/www/live/releases/69/vendor/bundle/ruby/2.2.0/gems/intercom-3.0.2/lib/intercom/request.rb:18:in `set_basic_auth'
/var/www/live/releases/69/vendor/bundle/ruby/2.2.0/gems/intercom-3.0.2/lib/intercom/request.rb:63:in `execute'
/var/www/live/releases/69/vendor/bundle/ruby/2.2.0/gems/intercom-3.0.2/lib/intercom/client.rb:90:in `execute_request'
/var/www/live/releases/69/vendor/bundle/ruby/2.2.0/gems/intercom-3.0.2/lib/intercom/client.rb:76:in `post'
/var/www/live/releases/69/vendor/bundle/ruby/2.2.0/gems/intercom-3.0.2/lib/intercom/api_operations/save.rb:26:in `save'
/var/www/live/releases/69/vendor/bundle/ruby/2.2.0/gems/intercom-3.0.2/lib/intercom/api_operations/save.rb:18:in `create'
/var/www/live/releases/69/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/performable_method.rb.....
```

Any ideas? Thanks!

**Comment by josler** [comment]
Hey @constantm,

That's a major intercom-ruby version upgrade from 2.x.x to 3.x.x; we use [semantic versioning](http://semver.org/) so to avoid being bumped major versions (which do not have backwards compatibility) you can use the following in your gemfile:

`gem 'intercom-ruby', '~> 2.5'`

I'm not sure what the problem is here, but it looks related to delayed_job not deserializing the client properly (not getting your app_id/api_key from secrets). You could look at creating the Intercom::Client outside of the scope of the job and re-using it.

**Comment by constantm** [comment]
It does indeed look like delayed_job for some reason doesn't have access to Rails.application.secrets - no idea why. I've set ENV variables as a workaround for now.
