### ISSUE TITLE
Add specific error tyes to avoid Intercom::UnexpectedError

### ISSUE THREAD

**Issue by Javierchik** [intercom/intercom-ruby#187]
Hi 

I'm using 'Intercom::Message.create' method to create some messages and when the user has 'unsubscribed_from_emails = true' the method raise an exception: " Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: This user is unsubscribed from emails and http_code: '403'. Please contact Intercom with these details. "  is there any gentle to handle this error in the gem?

Thanks

**Comment by josler** [comment]
https://github.com/intercom/intercom-ruby/issues/198

same for AuthenticationError.

**Comment by choran** [comment]
Hi @Javierchik ,
We reviewed this issue and I just wanted to update you. We dont plan to add any further specific errors here. The unsubscribed error is returned as part of the UnexpectedError so at least that can be handled to identify why the server did not process the request. Was there some other reason that you wanted a specific error here? i.e. was there some problem you were having that a specific error would resolve which you cannot currently handle. If you have a particular use case then please let us know and we can look into it again. So I will close this for now but as noted, if you think we are missing something here feel free to reopen and let me know and we can re-visit

**Comment by bpo** [comment]
@choran We've found this same issue frustrating (in fact we had a comment to "see issue #187 on intercom-ruby" because "unsubscribed from emails" is a special case that we want to be able to handle programmatically.

Intercom is built for a number of messaging purposes, only some of which should support unsubscribes. For example if we need to send a user a support message to assist them with their billing or credential information, the fact that they want to unsubscribe from marketing material shouldn't inhibit that.

Without adding specific error types we end up needing to parse the text returned by the Intercom API, and that seems unreliable at best.
