### ISSUE TITLE
The Messages API has serious limitations

### ISSUE THREAD

**Issue by peddinti** [intercom/intercom-ruby#199]
Hi i am trying to use the Messages API with email type and it has serious limitations that are a real concern.

1.) I can't add html blocks in body. For a email message type not supporting that is a problem. I can't have CTA buttons or anything, just plain simple message in a emails looks very unattractive and doesn't help.

2.) Can't send messages in bullk. If i send a message, it will appear in intercom dashboard in "Manual" tab. The API allows only sending messages to one user/contact at a time. so if i send messages to a 100 of them one at a time. all of them will appear as individual messages and i wont get combined stats. thats so bad

3.) No support for unsubscribe link. Seriously that is mandatory for the email messaging type API. the front end allows it.

4.) Not so serious problem, but good to have is use custom created templates. currently it allows only "plain" and "personal"... 

I like the events, contacts and User API. but given some limitations for messages in the front end i thought, the API would come to the rescue. But i feel this is not useful at all.

**Comment by josler** [comment]
Hey there @peddinti, thanks for writing in.

This is really a discussion for the API as a whole, rather than this particular Ruby client, however:

We're deliberately not supporting more advanced messaging structures through our API as we believe our product and custom-built editor there offers a much better experience - and generates message structures in a format which we can deliver on multiple devices.

The same goes for bulk messaging - the product has the concept of 'Auto Messages' which are a much better map for this; setting some conditions in which a message should be delivered, and some dynamic message content, and then letting our scheduling deliver these. We don't currently support Auto Messaging via the API currently.

We're aware of these limitations in the API currently, and do re-evaluate our stance on them from time to time, but have no current plans to offer these services through the API instead of through the website (which offers a much better experience).

**Comment by peddinti** [comment]
Thanks .. i agree this is more of a API discussion than ruby client. Auto Messages work great for "Users" not "Contacts" as these ppl are not doing any interactions on the platform. 

Again the front end is a great tool for composing messages. But it lacks the ability to schedule messages. This is important for messaging contacts.  

I guess this is not a right place to discuss about the API. but please let me know what would be the right contact for this. Because this is a serious problem that is undermining our ability to use Intercom.

**Comment by josler** [comment]
We have Auto Messaging (email only) for Contacts via the website, and you can schedule the time email messages get delivered too.

If you message in through Intercom itself, people there can give you a better run down and walk through the options there.
