### ISSUE TITLE
contacts not saving

### ISSUE THREAD

**Issue by peddinti** [intercom/intercom-ruby#200]
first i am getting a contact
`contact = IntercomClient.contacts.find_all(email: "email@domain")[0]`

it returns the Intercom::Contact object

then i do this:
`IntercomClient.contacts.save(contact)`

I am getting the following error. I am not even saving any new information

    Intercom::BadRequestError: Value:  not of type Numeric, String or Boolean
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/intercom-3.0.6/lib/intercom/request.rb:140:in `raise_application_errors_on_failure'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/intercom-3.0.6/lib/intercom/request.rb:94:in `parse_body'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/intercom-3.0.6/lib/intercom/request.rb:70:in `block in execute'
        from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:853:in `start'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/intercom-3.0.6/lib/intercom/request.rb:65:in `execute'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/intercom-3.0.6/lib/intercom/client.rb:90:in `execute_request'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/intercom-3.0.6/lib/intercom/client.rb:80:in `put'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/intercom-3.0.6/lib/intercom/api_operations/save.rb:24:in `save'
        from (irb):469
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'

**Comment by tute** [comment]
There is a similar report in https://github.com/intercom/intercom-ruby/issues/221 for the latest release. This can be considered duplicate I think.

**Comment by choran** [comment]
Hi @peddinti,
I have been unable to re-create this. You note that you are not making any changes before saving this so I wonder if there is some non UTF-8 character in your contact object which may be causing this. We did add some force encoding to change attributes to UTF-8 so that may have solved this.

I tried changing contacts  and saving them and just saving contacts as you have here was not able to get an error. Can you check if you are still getting a similar error? If you are then please re-open this issue and can you also provide the output of the contact you are trying to save. That way I can look at the attributes and see there is something there which may be causing this.
Thanks
Cathal

> contacts = intercom.contacts.find_all(email: "multiple@email.com")[0];
> contacts.name
=> "M2"
> contacts.custom_attributes
=> {}
> contacts.custom_attributes["M2a"] = "Test 2a"
=> "Test 2a"
> intercom.contacts.save(contacts)
> contacts.custom_attributes
=> {"M2a"=>"Test 2a"}
Or just saving without making any changes
> contacts = intercom.contacts.find_all(email: "multiple@email.com")[1];
> contacts.name
=> "M1"
> intercom.contacts.save(contacts)
