### ISSUE TITLE
Intercom::AttributeNotSetError: 'user_id' called on Intercom::Contact but it has not been set an attribute or does not exist as a method

### ISSUE THREAD

**Issue by tute** [intercom/intercom-ruby#235]
## Version info

  - intercom-ruby version: 3.3.0
  - Ruby version: 2.3.0

## Expected behavior

Convert lead into user without error message.

## Actual behavior

Following error comes up:

```
Intercom::AttributeNotSetError: 'user_id' called on Intercom::Contact but it has not been set an attribute or does not exist as a method
from /Users/tutec/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/intercom-3.3.0/lib/intercom/lib/dynamic_accessors_on_method_missing.rb:24:in `define_accessors_or_call'
```

## Steps to reproduce

 1. Have a lead and a user in Intercom
 2. Find both in a script
 3. Call `convert` on them

```ruby
intercom_user = intercom.users.find(email: email)
lead = intercom.contacts.find(email: email)
intercom.contacts.convert(lead, intercom_user)
```

---

I would expect you'd need to perform these steps with our data. If that's the case, let me know and I'll go through customer support.

Thank you!

**Comment by tute** [comment]
Alex from Intercom suggests:

```ruby
contacts = intercom.contacts.find_by(email: email) 
contact = contacts.first 
user = intercom.users.find(:user_id => user_id) 
intercom.contacts.convert(contact, user)
```

Not very different than my implementation, but now trying it.

**Comment by choran** [comment]
hi @tute 
The issue here is that when you use email with contacts.find an array will be returned. Hence the problems converting the lead. Instead you can use 
1/ intercom.contacts.find(user_id: "<USER_ID>"); or
2/ intercom.contacts.find(id: "<ID>");
Both of these will return a single user which you should be able to convert. Alternatively, as Alex suggested, contact.first should also work. I was able to convert a lead using either of these methods. We do have a tutorial series which has some examples you might find useful in this context. You can find it [here](https://developers.intercom.io/docs/adding-leads)

If you have any other issues let us know.
Cathal
