### ISSUE TITLE
Unable to delete contacts

### ISSUE THREAD

**Issue by thesmart** [intercom/intercom-ruby#257]
## Version info
  - intercom-ruby version: 3.5.1
  - Ruby version: 2.1.5

## Expected behavior

Should be able to delete contacts.

## Actual behavior

Can't delete contacts.

## Steps to reproduce
```
i_contacts = intercom.contacts.find_all email: email
puts i_contacts.count
i_contacts.each do |i_contact|
  intercom.contacts.delete(i_contact)
  puts 'deleted'
end
i_contacts = intercom.contacts.find_all email: email
puts i_contacts.count

```

## Logs

```
2
deleted
deleted
2
```

**Comment by thesmart** [comment]
Appears to be non-deterministic.  Sometimes I get `Intercom::ResourceNotFound: User Not Found`  and an output of:
```
2
```

**Comment by ngouy** [comment]
👍

**Comment by thesmart** [comment]
Intercom followed up with me on this, I was told by Intercom that this is due to their DB being eventually consistent.  They recommended I add sleep until their "DX team" can have a look at fixing.

**Comment by choran** [comment]
Hi @thesmart 
There can be a delay sometimes when you delete users or contacts. It should only take a few seconds but sometimes it can take a little longer. Let me do some further investigation into the eventual consistency side of your question in relation to the "non-deterministic" results you are seeing.

**Comment by choran** [comment]
@thesmart yeah, I checked this out and the results you are seeing are related to eventual consistency. Like I said above, there can be a delay before users/contacts are deleted. And during this delay you can get different results due to eventual consistency. So you should take this into consideration if you are when checking/updating data that you may have deleted. There should only be a very short period ie a matter of seconds) where you get the "non-deterministic" results.
As such there is nothing we would consider "fixing" since eventual consistency is a design considering for our underlying architecture. Please re-open this if you are having any other issues when you try and delete users/contacts.
