### ISSUE TITLE
curious behavior when giving incomplete query info

### ISSUE THREAD

**Issue by jjb** [intercom/intercom-ruby#302]
## Version info
- intercom-ruby version: 3.5.9
- Ruby version: 2.3.1
## Expected behavior

Exception raised from client library and/or error returned from server
## Actual behavior

The same 7 conversations returned for every query.
## Steps to reproduce

```
[16] pry(main)> @client.conversations.find_all(email: 'asdfasdfasdf').count
=> 7
[17] pry(main)> @client.conversations.find_all(email: 'asdfasdfasdf123').count
=> 7
[18] pry(main)> @client.conversations.find_all().count
ArgumentError: wrong number of arguments (given 0, expected 1)
from /var/lib/gems/2.3.0/gems/intercom-3.5.9/lib/intercom/api_operations/find_all.rb:7:in `find_all'
```

**Comment by choran** [comment]
Hi, 
thanks for reaching out.
I think this only occurs when you dont specify a type right?
e.g. convos_list = intercom.conversations.find_all(email: "example@example.com", type: 'user').count
This will return the correct count
Whereas 
convos_list = intercom.conversations.find_all(email: "NOexample@example.com", type: 'user').count
will return a User Not Found (Intercom::ResourceNotFound) error
and 
convos_list = intercom.conversations.find_all(email: "example@example.com").count
will return all conversations
Using only one argument you get the correct behaviour
convos_list = intercom.conversations.find_all(unread: true).count
So it looks like we expect a min of 1 arg but dont specify what that arg is. It is valid when it is state but not when it is only the email, in which case you need another argument or it defaults to all conversations.
Does this make sense? 
Like I said, I think we should check for the argument which is specified since it seems that in some cases it is not valid to have just one argument

**Comment by jjb** [comment]
thanks for your response.

so, in this case it's accepting the argument but not using it. IMO this should not happen.

**Comment by choran** [comment]
Np, yeah, I agree. Like I said, we should check for the argument which is specified since it seems that not all single argument cases are valid. In that case it would return an error when you specify just the email and not they type.

**Comment by choran** [comment]
Hi @jjb 
Just to update here.
We are tracking this issue internally, i.e. the need to return an error when the type form is used incorrectly rather than returning all results.
We just need to check if people are using it in the incorrect way, either way it is something we will aim to change on the API.
As a result I will close the issue here since we will not make the changes in the SDKs.
This was one option but does not seem like the best approach.
thanks and  feel free to reopen if you have any further questions
Cathal
