### ISSUE TITLE
Include `find_all` to segments service

### ISSUE THREAD

**Issue by morellan** [intercom/intercom-ruby#325]
## Version info
  - intercom-ruby version: 3.5.5
  - Ruby version: 2.3.1

## Expected behavior
Since the Segments API can receive the  `include_count` param, it will be great to do `intercom.segments.find_all(include_count: true)`

## Actual behavior
Only `all` available without any params

**Comment by choran** [comment]
Hi, thanks for the suggestion. I think I understand, you want a way to list all segments so that they return the segment object with the count by specifying the parameter include_count=true.
I guess in the other uses of find_all they are using filtering params such as email. The include_count is not really a filtering param but I do see that you want a way to list all your segments including the count attribute. Let me know if you think I have picked this up incorrectly. I will add this to our internal backlog for feature to update the SDKs with.  In the meantime I will close this and thanks again for the suggestion.
