### ISSUE TITLE
Question: Submit bulk job vs. API rate limit

### ISSUE THREAD

**Issue by aimee-ault** [intercom/intercom-ruby#332]
I'm calling `client.users.submit_bulk_job` and passing it an array of 100 users. The user data is generated from local database records and there are 367 total, so 4 calls total are happening to `client.users.submit_bulk_job`. The first call finishes and I get a response object. The second call, I immediately get a message that the rate limit has been exceeded. Shouldn't 4 calls to the bulk job endpoint = 4 api calls? No other requests are being made that I'm aware of. The client says I have 83 of 83 remaining requests. 

Is each item in the bulk job getting counted as its own request? I checked this repo and it looks like it's posting all at once to its own bulk jobs endpoint so I don't understand how I'm exceeding it.

## Version info
  - intercom-ruby version: 3.5.11
  - Ruby version: 2.2.6p396

## Expected behavior
4 API requests made (100 items, 100 items, 100 items, 67 items)

## Actual behavior
83+ API requests? despite calling this method 4 times

**Comment by pgaspar** [comment]
I'm also seeing this on our implementation.

We're also passing 100 users per bulk request and we're seeing the same rate limiting error every time we send 2 of these bulk requests in the same 10 second block.

If each individual record counts towards the rate limit, I'm not even sure what happens to the 17 records we send over the 83 limit, in each 100-record bulk request. Are they ignored?

I would also expect 1 bulk request to count as 1 request towards rate limiting, not 100.

**Comment by brianw** [comment]
Requests to our bulk API cost 1 operation per user update (not per request). This is definitely confusing and not at all obvious though. Your rate limit is applied over a 10 second window, which also makes it more difficult to reason about.

Our API rate limits are designed to protect our storage infrastructure from being unfairly overloaded by a single customer, that's why cost is applied at operations against storage rather than HTTP operations (which are cheaper compared to database writes). 

Improving the developer experience of our APIs is something important we're working on. I'm sorry about the confusion here, we could provide a much better experience.

**Comment by aimee-ault** [comment]
@brianw Is there no true way then to batch update your userbase in Intercom then? I filed the question on behalf of Treehouse (teamtreehouse.com) and our API rate limit is already pretty heavily hit in realtime usage by our customers. We have new custom attributes that we're trying to backfill for existing users.

**Comment by RKushnir** [comment]
This started happening for me only yesterday. And the [reference](https://developers.intercom.com/reference#rate-limiting) still says "rate limit is 500 *requests* per minute per app". Have the limiting rules just changed? I couldn't find any announcements.

**Comment by brianw** [comment]
Followed-up through Intercom.

**Comment by brianw** [comment]
Hi @RKushnir, sorry the documentation is wrong here I'm afraid, I'll update it now.

**Comment by kimroen** [comment]
> Followed-up through Intercom.

@brianw Would you mind sharing the answer to aimee-ault's question here? We have the same use case: backfilling new custom attributes for existing users.

**Comment by rukai-kooboo** [comment]
We also have this question. We have monthly subscription data, that may change every month, for users, they need to update their information in Intercom, so that we can send campaign emails based on the latest information. We now have about 500,000 users, almost 200K to 400K of them need update every month, it now takes more than 20 hours to sync via Bulk update API. Any solution to get a fast rate_limitation?

**Comment by chrisnicola** [comment]
@brianw is it not contradictory that the rate limit is 83 per 10 second window but the bulk API limit is 100? Both of these can't be limits.

I also agre with @rukai-kooboo these limits are excessively low.

**Comment by camt** [comment]
@theandrewykim @brianw what is the current recommended method of backfilling User and Company data? As per @aimee-ault I am needing to backfill as new custom attributes are added to our model. 

Am I going to need to just batch these into, say, 50 requests/minute? Or is there now a way to do bulk updates without internally triggering the rate limits anyway? Even doing 50/min is probably going to break us, as we will be encroaching on the 83/min limit with normal usage as it is.

**Comment by AndreiRailean** [comment]
perhaps that new truckload of VC cash could be used to add a bulk api that doesn't break your DB writes

**Comment by snkashis** [comment]
Are there any updates planned on this topic? Even the bulk CSV uploader @chrisnicola would be a significant improvement here. I think a lot of people need more robust bulk upserting here.

**Comment by summera** [comment]
Any updates here? We have a need to bulk update users in the background but circumventing these rate limits is really going to make things difficult.

**Comment by bsiver** [comment]
I would love to hear if there's been any updates on adding leniency to the rate limits applied to the bulk API.  Backfilling our users with new custom attributes has become a common ask, and the process is painfully slow for us.
