### ISSUE TITLE
can't create a message

### ISSUE THREAD

**Issue by ngouy** [intercom/intercom-ruby#345]
When I'm trying to reproduce the same thing explained in docs by creating a user initiated message through `id: user.id` or `email: whatever@example.com` it doesn't works

## Version info
  - intercom-ruby version: 3.5.16
  - Ruby version: 2.4.1

## Expected behavior

I have a valid Intercom Client (eg: i can create a user)
I want to create a user initiated message

## Actual behavior

Creating a user works fine.
Creating a message :
```ruby
client = MyIntercomIntegrationManagerModel.first.client
# => => #<Intercom::Client:0x007fc4dd7a55e0 @username_part="***********", [...] >
user = client.users.all.first
# => #<Intercom::User:0x007fc4e7083d20  [...], @id="59525a34976ffb**********", [...], @email='123@example.com', [...] >
client.messages.create({
    from: {
        type: 'user',
        id: user.id
    },
    body: 'test'
})
```
it throw : 
`Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: Not authorized to access resource and http_code: '401'. Please contact Intercom with these details` <br><br>while :
```ruby
client.users.create(email: '321@example.com')
# => #<Intercom::User:0x007fc4e7150988 @changed_fields=#<Set: {}>, @custom_attributes={}, @id="**********", @user_id=nil, @anonymous=false, @email="321@example.com", @phone=nil, @name=nil, @pseudonym=nil, @avatar=#<Intercom::Avatar:0x007fc4e7133d60 @changed_fields=#<Set: {}>, @image_url=nil>, @app_id="******", [...] >
```
works like a charm

Am I missing/misunderstanding something or ... ?

**Comment by choran** [comment]
Hi @ngouy,
It looks like it is an access token issue.
You will need to apply for extended permissions on your access token, I think you might only have regular permissions which may be the problem here.
Once you get the extended permissions this should work.
If not please re-open this and let me know. 
Alternatively, if you reach out to our CS team they should also be able to help you with any access token issues
thanks
Cathal
