### ISSUE TITLE
3.5.22 Intercom::BadRequestError exception "bad 'type' parameter"

### ISSUE THREAD

**Issue by P9GIT** [intercom/intercom-ruby#367]
After updating to version 3.5.22 our code broke with exception:

Intercom::BadRequestError exception "bad 'type' parameter"

when trying to save User objects in Intercom.

Looks like the now returning "type" field is rejected here for certain responses:
https://github.com/intercom/intercom-ruby/blob/61c8bc3f749a2351026733178f3311028207cc27/lib/intercom/request.rb#L104

because:
https://github.com/intercom/intercom-ruby/commit/61c8bc3f749a2351026733178f3311028207cc27#diff-88208777fbb69fa3181dc0087c937fcf

With 3.5.21 our coded seemingly worked, but I wonder if the masked type param did return with an error that now is considered in code?

We POST:
18851 TID-1uw6n8 IntercomWorker JID-8e408bc0e8359ac18d1930a3 DEBUG: {"custom_attributes"=>{"total_unread_count"=>0, "status"=>"activated", "customer_contact"=>"no", "role"=>"admin", "phone"=>"", "billing_contact"=>"no"}, "email"=>"xxx@panorama9.com", "name"=>"Thomas", "companies"=>[#<Intercom::Company:0x0000000cdfaf28 @changed_fields=#<Set: {"name"}>, @custom_attributes={"customer_id"=>16, "path_win_with_deps"=>"xxx", "path_win_without_deps"=>"xxx", "path_osx"=>"xxx", "path_linux"=>"xxx", "country_code"=>"DK", "subscription_provider"=>"stripe", "subscription_name"=>"", "subscription_interval"=>"", "subscription_card"=>"yes", "account_state"=>"active", "remote_created_at"=>1443084703, "contact_email"=>"xxx@panorama9.com", "contact_email_validated"=>"yes", "billing_email"=>"xxx@panorama9.com", "billing_email_validated"=>"yes", "status"=>"activated"}, @type="company", @company_id="4d346133eca01e253e000005", @id="533d55e37299760a5000115d", @name="democlient">], "id"=>"5361f785750b3209a900093a", "user_id"=>"5065d2faeca01e1d04000002"}

and get response:

18851 TID-1uw6n8 IntercomWorker JID-8e408bc0e8359ac18d1930a3 DEBUG: {"type"=>"error.list", "request_id"=>nil, "errors"=>[{"code"=>"bad_request", "message"=>"bad 'type' parameter"}]}

What does this error message signify?

## Version info
  - intercom-ruby version: 3.5.22
  - Ruby version: 2.2.5

## Expected behavior

User is updated and no exceptions raised

## Actual behavior

Exception raised: Intercom::BadRequestError 
Message: "bad 'type' parameter"

User is not updated

## Steps to reproduce
 1. 
 2. 
 3. 

## Logs
An Intercom::BadRequestError occurred in background at 2017-11-14 12:44:52 UTC :

  bad 'type' parameter
  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.22/lib/intercom/request.rb:155:in `raise_application_errors_on_failure'

-------------------------------
Backtrace:
-------------------------------

  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.22/lib/intercom/request.rb:155:in `raise_application_errors_on_failure'
  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.22/lib/intercom/request.rb:104:in `parse_body'
  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.22/lib/intercom/request.rb:72:in `block in execute'
  /usr/local/rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:853:in `start'
  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.22/lib/intercom/request.rb:67:in `execute'
  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.22/lib/intercom/client.rb:113:in `execute_request'
  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.22/lib/intercom/client.rb:93:in `post'
  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.22/lib/intercom/api_operations/save.rb:27:in `save'
  /var/www/portal/lib/panorama9/workers/intercom_worker_base.rb:160:in `update_intercom_user'
  /var/www/portal/lib/panorama9/workers/intercom_worker.rb:103:in `block in handle_dashboard_user_update'
  /var/www/portal/lib/panorama9/workers/intercom_worker_base.rb:84:in `intercom_exceptions_handler'
  /var/www/portal/lib/panorama9/workers/intercom_worker.rb:47:in `handle_dashboard_user_update'
  /var/www/portal/lib/panorama9/workers/intercom_worker_base.rb:21:in `perform'

**Comment by choran** [comment]
HI @P9GIT 
Thanks for reaching out about this and for the logs provided. That helped in trying to understand the issue more quickly.
You are correct, in 3.5.22 we made a change which addressed the type parameter.
What seemed to be happening previously was that they type parameter was never being sent as part of the API request. It was basically being ignored. The change was to raise an error if the type parameter was being send to indicate that this was occurring rather than failing silently.
From your past I see that they type you were passing in was for 'company'. I dont think you need to submit this type when adding a user to companies. You can see from the API ref [here](https://developers.intercom.com/reference#companies-and-users). 
But I might be missing something so I was wondering if you could clarify why you are using the type parameter here?
Also, could you provide the full code snippet you are using, that might make it easier to repro this.
It might be that I am missing something in how the type is being used. For example, when adding users to companies you only need to supply the company_ID. But there may be some use case where you need to use the type?
Thank again for raising this 
Cathal

**Comment by P9GIT** [comment]
Hi @choran 

Thanks for getting back on this.

We don't explicitly add the type parameter.
It is among the fields of the retrieved companies object array when we fetch a user.
I guess we just round trip the type param which is why it is found in the posted data. 

Anyway here is a snippet of code from our Intercom worker below. Whenever a change happens to our user (name, company info or custom attribute data like role or activation status) we update the user in Intercom and include company info which also might be updated.

The "intercom_user_hash" var contains updated values for the user denoted by the "id" parameter/supplied user object parameter "intercom_user". The hash does not include a "type" parameter anywhere.

As you can see we read of the current company from the fetched intercom User instance and update some of the fields. As the type param is now returned in the company instance it will become part of the data we ship for the update operation.

So from what you are writing removing the "type" field from the company instance would solve this problem?

`def update_intercom_user(intercom_user_hash, id, intercom_user = nil)
    if intercom_user.nil?
      # get intercom user
      intercom_user = intercom_client.users.find(user_id: id) #+1 request to Intercom.io API
    end

    # keep :custom_attributes and :companies different with intercom user fields, because it is complex type data
    custom_attributes = intercom_user_hash.delete(:custom_attributes)
    companies = intercom_user_hash.delete(:companies)

    if custom_attributes
      custom_attributes.each{|field, value| intercom_user.custom_attributes[field] = value}
    end

    if companies
      # We have only one company for intercom user. So just get first company
      # Note: this not call request to Intercom.io API. So, call 'companies' not change rate api counter.
      intercom_company = intercom_user.companies.first

      if intercom_company.nil?
        # will create new companies for intercom user
        intercom_user.companies = companies
      else
        # update company
        company = companies.first
        company_custom_attributes = company.delete(:custom_attributes)

        if company_custom_attributes
          company_custom_attributes.each{|field, value| intercom_company.custom_attributes[field] = value}
        end

        # update company fields via Intercom::Company setters
        company.each{|field, value| intercom_company.send("#{field}=", value)}
        # set updated company
        intercom_user.companies = [intercom_company]
      end
    end

    # update user fields via Intercom::User setters
    intercom_user_hash.each{|field, value| intercom_user.send("#{field}=", value)}

    # save intercom user
    intercom_client.users.save(intercom_user) #+1 request to Intercom.io API
  end`

**Comment by choran** [comment]
@P9GIT thanks for the update.
Firstly, yes, if you leave out the type field it should solve the issue here.
Secondly, in relation to your use case where you say you might have to update the user, you may not need to send the company in each time. e.g. if you update the company then you would not need to update the user. The user will have the company associated with it, so if that company is updated the user will automatically inherit that change. 
You can pass through the company object as you are at the moment also if you want to update it that way i.e. via the user. In that case then you would need just to remove the type field.
I guess from your description you do not know what have changed so you need to pass through every attribute just in case it has changed to make sure it is updated. In that case I think the simplest thing to do is to remove the type field and this should work.
Let me know if you are still having issue after that.
Thanks
Cathal

**Comment by P9GIT** [comment]
Hi @choran 

Removing the "type" param solved the issue.

Thanks!
Thomas.

**Comment by choran** [comment]
@P9GIT great, thanks for the update. 
Glad that resolved the issue and thanks for highlighting it, I had not thought about that use case
