### ISSUE TITLE
Is there better filtering options for /conversations and /count requests?

### ISSUE THREAD

**Issue by mik356ua** [intercom/intercom-ruby#379]
Hello! I need to count all my company conversations for a certain period of time (between `Time.now.beginning_of_day` and `Time.now.end_of_day`) but have no idea how to do it a proper way. Currently I'm using this approach:
```ruby
    conversations = []
    intercom.conversations.find_all(sort: :created_at, order: :desc).each do |c|
      break if c.created_at < Time.now.in_time_zone("Pacific Time (US & Canada)").beginning_of_day
      puts "Conversation ID#{c.id} -- created_at: #{c.created_at.in_time_zone("Pacific Time (US & Canada)")}"
      conversations.push(c)
    end
    puts "Total conversations today: #{conversations.count}"
```
But I bet there must be a better way if I could use filter params in initial request. I was trying to use `before`, `after`, `created_since` query params, but it seems those are not working. I did no find any info in docs which filter options are supported for `/conversations` or `/count` endpoints. Can you add this info and if there is no support for such filtering can you implement it in your API please? It would be really helpful. Thanks!

**Comment by choran** [comment]
Hi @mik356ua,
I think your use case makes sense and I can see how it might be slightly more awkward to implement that at present. i.e. you need to check for the timeframe yourself as you have in your example.
Like you said, this is a restriction with the API filters at the moment. I think a created_since filter would help here. It would allow you to implement your search by looking for conversations that were created in the las X num of days like we have [here](https://developers.intercom.com/reference#list-users) on the user endpoint.
We are reviewing aspects of the conversation endpoint to better understand what improvements we can make and I will include this as a use case we need to consider. For now I will close this issue since it is related to the API. We will provide an update if we make any changes to the conversations API that may help in these type of use cases.
We usually make these announcements via the [Intercom dev blog](https://developerblog.intercom.com/)

**Comment by angusprintify** [comment]
Any update on this?

**Comment by andrey-lizunov** [comment]
Filters by message type and created_at are very logical. Have no idea why they do not exist.
