### ISSUE TITLE
Question: How to find user/company by custom attribute?

### ISSUE THREAD

**Issue by tisba** [intercom/intercom-ruby#382]
## Version info
  - intercom-ruby version: 3.5.23
  - Ruby version: 2.4.1

## Expected behavior

I expect that I can query the API for resources (e.g. users or companies) which have a specific custom attribute set.

## Actual behavior

I cannot find an example or anything in regard to how to formulate a query for custom attributes.

I've tried multiple things, but could not get it to work. I've tried queries like:

```ruby
client.users.find(custom_attributes: { uid: "abc42" })
```

or

```ruby
client.users.find(custom_attributes_uid: "abc42")
```

which returns a `Intercom::User` object (and not a error if the user does not exist), but it looks like it is not populated. This would actually be another question: How can I tell from the result if something was found or not? Checking if `Intercom::User#id` is `nil`?

**Comment by theandrewykim** [comment]
Hey @tisba ! 
Right now the ability to find users that contain a specific value for a custom attribute isn't currently possible. This is more of a feature request when it comes to functionality surrounding our [API](https://developers.intercom.com/v2.0/reference#view-a-user). You would have iterate through your user list and search for users with the specific attribute you're looking for. The only parameters you can use the `find` call for are for the `id`, `user_id` and `email` fields.

In regards to acknowledging when a user query isn't returning a valid body, we do raise a User Not Found error but only when using one of the valid search parameters. Otherwise, the Intercom::User object will return a list of users which you can fetch by doing `intercom.users.find({invalid: 'search'}).users`

I'm going to close this issue out for now, as again, this is behavior that pertains to our REST API, not behavior that is specific to this Ruby gem, but definitely noted by the team!

**Comment by Jeromearsene** [comment]
#230 that's the same idea no ?

**Comment by cfjedimaster** [comment]
I'm doing some work for a client now in June, 2019, and it looks like this still isn't possible? To search via custom attribute I mean. Correct?

**Comment by jonnyom** [comment]
@cfjedimaster correct! Right now it's not possible.

It's something we're hoping to start looking into though 👍

**Comment by jonnyom** [comment]
@cfjedimaster @Jeromearsene @tisba just looping back here.

We've now built our Customer Search API which is available in the Unstable version of our API.

https://developers.intercom.com/intercom-api-reference/v0/reference#search-for-customers

You can search by any combination of attributes, sort on any attribute and generate complex AND and OR queries!

We've released it in the latest version of the SDK https://github.com/intercom/intercom-ruby#search-for-customers

Hope this helps 😄
