### ISSUE TITLE
Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: scroll already exists for this app and http_code: '400'.

### ISSUE THREAD

**Issue by andrewhavens** [intercom/intercom-ruby#415]
I'm trying to fetch notes for users and keep getting 404s. So I've been trying variations of passing `id`, `user_id`, `email` params. So I've been stopping my script and restarting it. I'm guessing that my API client is only allowed to have one scroll param and it hasn't expired yet from when I stopped my script and restarted it. This must have happened with my `INTERCOM.users.scroll` call since it was not wrapped in a begin/rescue.

## Version info
  - intercom-ruby version: 3.5.25 (latest)
  - Ruby version: 2.5.1

## Expected behavior
Intercom API allows me to make a new scroll request and does not require me to use the same scroll param if I'm starting and stopping my script. Even if my scroll param is invalid, it shouldn't raise an exception. It should wait until it can validly make a request.

## Actual behavior
Script raises error when making a scroll request too soon after making a previous scroll request.

## Steps to reproduce
```ruby
    INTERCOM.users.scroll.each do |user|
      begin
        notes = INTERCOM.notes.find_all(id: user.id)
        notes.each {|n| puts n.body }
        puts
      rescue => e
        puts e.inspect
      end
    end
```

**Comment by choran** [comment]
Hi @andrewhavens 
Unfortunately, with scroll there is a [timeout associated](https://developers.intercom.com/intercom-api-reference/reference#iterating-over-all-users) with the scroll param. This is an elastic search requirement with using scroll. We understand the issues that this may cause so previously we looked into what we could do to help customers that were encountering the same problem as yourself. 

We added functionality so that when you reach then end of your scroll resources i.e. the last list returned is empty, then your scroll param automatically resets. 
Unfortunately, we could not find any suitable way to reset the scroll parameter in other circumstances and any other time units smaller than 1m resulted in more timeouts during general usage for customers. 

We do understand that listing large amounts of resources is important so we are looking at other ways of addressing this which may alleviate the need to use functionality such as scroll. We will provide updates on this when we have more information.

I will close this for now since this is not an SDK issue but thanks for raising it and it is definitely something we are looking into here.
Feel free to let me know if you have any other questions on this
