### ISSUE TITLE
Name is not copied over when converting lead to user

### ISSUE THREAD

**Issue by andrewhavens** [intercom/intercom-ruby#425]
This may be more of an API bug, but anyway...

## Version info
 - intercom-ruby version: 3.5.25
 - Ruby version: 2.5.0

## Expected behavior
Lead name is copied over because User name is nil.

## Actual behavior
Lead name is not copied over.

## Steps to reproduce
```ruby
lead = INTERCOM.contacts.find_all(email: email).first
#=> #<Intercom::Contact @name="Test Name", ...
user = INTERCOM.users.find(email: email)
#=> #<Intercom::User @name=nil, ...
result = INTERCOM.contacts.convert(lead, user)
#=> #<Intercom::User @name=nil, ...
```

**Comment by andrewhavens** [comment]
Also, the documentation seems to imply that all these types of things would get merged onto the User record. It doesn't list any exception for name. https://developers.intercom.com/intercom-api-reference/reference#convert-a-lead

There may be other attributes that aren't copied over, but I just noticed this one.

**Comment by choran** [comment]
Hi @andrewhavens 
I think the issue here is that the Ruby sdk does not allow you to convert a lead to a new user.
There are two ways that you can convert a lead, 
1/ convert a lead to an already existing user
2/ convert a lead to a new user

in 1 some of the attribute such as name are not copied over
in 2 you should be able to copy over attributes such as name when converting a lead to a new user.
Since this functionality is available via the api it should be also possible via the SDK so we do need to add this option to the sdk

Would you like to convert to a new user or always to an existing user?

**Comment by andrewhavens** [comment]
Maybe I'm confused, but I thought this automatically created a user record if it did not exist yet:
```ruby
contact = intercom.contacts.find_all(email: email).first
intercom.contacts.convert(contact, Intercom::User.new(email: email))
```

This is what I would want:
1. If the user does not yet exist, converting a lead creates a user and copies name (and all other details)
2. If the user exists, and the name on the user record is nil, converting a lead copies the name to the user record

**Comment by choran** [comment]
Yeah, it is a fair point. I think there was a view that the when a user already exists then any of the identifiers such as id, user_id or email should never be updated. It can be quiet tricky to identify rules for priority and in some cases people did not want the names updated in users under any circumstances. So I think this was the 'safest' approach i.e. to leave it up to the dev themselves to decide what to do.
However, we should definitely make it clearer how this operates since I think it is confusing both in the API and the SDK.
Thanks for the update and the clarification and I will close this issue now.
