### ISSUE TITLE
Add clarity on how to assign conversations to teams

### ISSUE THREAD

**Issue by andrewhavens** [intercom/intercom-ruby#433]
Sorry, this is a documentation request. I can't figure out how to assign a conversation to a team. I think I've done it before, but I can't figure out how to do it now. I can see the team when I list admins:

```ruby
INTERCOM.admins.all.each {|a| puts a.inspect } # list inboxes
```

But I get an error when I try to assign the conversation to a team. I know that the conversation and team exist:

```ruby
team_id = '12345'
INTERCOM.conversations.assign(id: conversation_id, admin_id: team_id, assignee_id: team_id)
# Intercom::ResourceNotFound
```

**Comment by tanasegabriel** [comment]
Hey @andrewhavens 👋 The issue here seems to come from the fact that you're using `team_id` as the value of the `assignee_id` parameter.

Teams are not actually fully fledged admins, so they cannot perform operations such as assigning a conversation. If you could use the id of an actual admin, that call should work.

So it'd be something like:

```ruby
intercom.conversations.assign(id: <conversation_id>, admin_id: <admin_id>, assignee_id: <team_id>)
```

**Comment by choran** [comment]
closing this since the change has been made on the readme for clarification
