### ISSUE TITLE
The error of type '' is not recognized. It occurred with the message: Company already exists. and http_code: '400'. Please contact Intercom with these details.

### ISSUE THREAD

**Issue by aurelien-reeves** [intercom/intercom-ruby#448]
`intercom.companies.create` sometimes raise a "company already exists" exception.
It happened only a few times - really not that often. I just wanted to report it to you.

## Version info
  - intercom-ruby version: 3.5.9
  - Ruby version: 2.5.3

## Expected behavior
The company is updated if it already exists

## Actual behavior
An exception is raised

## Steps to reproduce
No reproduction has been found. This is absolutely not systematic

## Logs
The error of type '' is not recognized. It occurred with the message: Company already exists. and http_code: '400'. Please contact Intercom with these details.

It happened:
2018-11-14T16:25:35.016Z
2018-11-22T01:06:40.021Z

**Comment by jonnyom** [comment]
Hey @aurelien-reeves thanks for opening this.

As this seems to be an implementation issue with the API itself, rather than with the SDK, I'm going to close this out.

If you'd like to write into our support team at https://developers.intercom.com/building-apps/docs they'll be able to work with you on a solution, or open up an internal tracking issue for us to work on.
