### ISSUE TITLE
Undefined method `custom_attributes'

### ISSUE THREAD

**Issue by subasvayu** [intercom/intercom-ruby#451]
I just got undefined method `custom_attributes' while doing
intercom_user.custom_attributes["email"] = @user.email
How this issue occurs? 

## Version info
  - intercom-ruby version: 3.6.2
  - Ruby version: 2.3.7

## Expected behavior
It needs to update the intercom user.

## Actual behavior
Shows Undefined method `custom_attributes' for #<Intercom::ClientCollectionProxy:>

## Steps to reproduce
 intercom = Intercom::Client.new(token: token)
 @user = User.find(user_id)
intercom_user.custom_attributes["email"] = @user.email

## Logs
NoMethodError: undefined method `custom_attributes' for #<Intercom::ClientCollectionProxy:0x000000000fbe89f8>
from (pry):14:in `perform'

**Comment by andrewhavens** [comment]
@subasvayu You didn't show where your `intercom_user` variable comes from. Is it coming from something like `intercom.users.all`?

**Comment by theandrewykim** [comment]
@subasvayu It looks like you are looking for custom attributes belonging to a collection proxy. Like user @andrewhavens  mentions - this likely means you're grabbing this from a collection of users rather than a specific user! If you are indeed using something like
`intercom.users.all` - try grabbing the first user and making the same call from there. Closing for now!
