### ISSUE TITLE
Contacts API Find method seems to return a client response object instead

### ISSUE THREAD

**Issue by nbantatua** [intercom/intercom-ruby#519]
## Version info
  - intercom-ruby version: 4.0.1
  - Ruby version: ruby 2.5.3p105

## Expected behavior
`user = intercom.contacts.find(email: 'xxxx@xxx.com')` should yield a contact object which should be used for other calls like `intercom.contacts.delete(user)`

## Actual behavior
`user` not an actual `Intercom::Contact` object

## Steps to reproduce
 1.  `intercom = Intercom::Client.new(token: ENV['INTERCOM_ACCESS_TOKEN'], api_version: '2.0')`
```
=> #<Intercom::Client:0x0000561b940fcb88 @token="XXXXXXXXXXXXXXX=", @api_version="2.0", @base_url="https://api.intercom.io", @rate_limit_details={}, @handle_rate_limit=false, @timeouts={:open_timeout=>30, :read_timeout=>90}>
```

 2.  `user = intercom.contacts.find(email: 'some@email.com')`
```
=> #<Intercom::Contact:0x0000561b941912d8 @changed_fields=#<Set: {}>, @custom_attributes={}, @client=#<Intercom::Client:0x0000561b940fcb88 @token="XXXXXXXXXXXXXXXXXXXXXXXXXX=", @api_version="2.0", @base_url="https://api.intercom.io", @rate_limit_details={:limit=>167, :remaining=>167, :reset_at=>2020-03-19 07:35:10 +0000}, @handle_rate_limit=false, @timeouts={:open_timeout=>30, :read_timeout=>90}>, @type="list", @data=[ACTUAL_CONTACT_OBJECTS], @total_count=62, @pages=#<Intercom::Pages:0x0000561b941825d0 @changed_fields=#<Set: {}>, @type="pages", @next={"page"=>2, "starting_after"=>"xxxxxxxxxx="}, @page=1, @per_page=10, @total_pages=7, @client=#<Intercom::Client:0x0000561b940fcb88 @token="XXXXXXXXXXXXXXXXXXXXXXXXXX=", @api_version="2.0", @base_url="https://api.intercom.io", @rate_limit_details={:limit=>167, :remaining=>167, :reset_at=>2020-03-19 07:35:10 +0000}, @handle_rate_limit=false, @timeouts={:open_timeout=>30, :read_timeout=>90}>>>
```

**Comment by murtron** [comment]
Hey @nbantatua, the issue here is that find contact by email is not supported in [API version 2.0](https://developers.intercom.com/intercom-api-reference/reference#get-contact). You must use the `id` field to find a contact instead.

As a result, `intercom.contacts.find(email: xxx)` isn't supported in version 4.0 of this SDK. The `email` param is actually being ignored and it behaves like a `GET /contacts` request which returns an unfiltered list of contacts.

I would suggest using contact search instead:
```
contacts = intercom.contacts.search(
  "query": {
    "field": 'email',
    "operator": '=',
    "value": 'some_contact@example.com'
  }
```
Let me know if that works for you 👍 

I'll look into blocking these types of query in the code and getting this documented. Thanks for reporting it!

**Comment by Chadh13** [comment]
@murtron - Would you mind documenting this as well for what was formerly known as `user_id` and is now called `external_id`?

I experienced a lot of pain during our migration to API V2.0 simply because it mostly removed the utility and value of the `external_id` value for individual lookup and operations. You are no longer able to lookup and interact with a Contact through an `external_id` unless you wanted to run 2 API calls (first a search, then a new call using Intercom's contact `id`) for everything. 

Even in those cases, you encounter a lot of issues with race conditions and API caching where any update takes about 30 seconds or longer to begin appearing in a search collection.

**Comment by nbantatua** [comment]
Thank you for the clarification @murtron I might go through with either caching `id` yield into our end or utilizing `external_id` field instead.

**Comment by giovannibonetti** [comment]
Using `external_id` has been working fine for us with SDK v4! 👍 

```ruby
intercom = Intercom::Client.new(token: token, api_version: '2.0')
query = { query: { field: 'external_id', operator: '=', value: user.id.to_s } }
contact = intercom.contacts.search(query)[0]
```

**Comment by bbugh** [comment]
THANK YOU @giovannibonetti. I cannot believe we can't search by external id with `find`.

One thing I noticed though is that in v4.1.2, if the `external_id` isn't found, it throws an `Intercom::ResourceNotFound: Resource Not Found` instead of returning `nil`. I can't think of any time I want my search to throw an exception when it can't find something rather than just returning an empty set, but here we are. I had to use this code:

```ruby
begin
  search_result = intercom.contacts.search(query)[0]
  contact_found = true
rescue Intercom::ResourceNotFound
  search_result = OpenStruct.new
  contact_found = false
end
```
